//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.JobReports = new HashSet<JobReport>();
        }
    
        public System.Guid Job_Id { get; set; }
        public int Job_Type { get; set; }
        public bool Job_Status { get; set; }
    
        public virtual ICollection<JobReport> JobReports { get; set; }
    }
}
