//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobReport
    {
        public System.Guid JobReport_Id { get; set; }
        public System.Guid JobReport_JobId { get; set; }
        public int JobReport_Progress { get; set; }
        public string JobReport_Commit { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
