//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jurisdiction
    {
        public Jurisdiction()
        {
            this.Users = new HashSet<User>();
        }
    
        public System.Guid Jurisdiction_Id { get; set; }
        public string Jurisdiction_Name { get; set; }
        public string Jurisdiction_Description { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
