//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.VMs = new HashSet<VM>();
        }
    
        public System.Guid User_Id { get; set; }
        public string User_Username { get; set; }
        public string User_Password { get; set; }
        public System.Guid User_Jurisdiction { get; set; }
        public bool User_IsDel { get; set; }
    
        public virtual Jurisdiction Jurisdiction { get; set; }
        public virtual ICollection<VM> VMs { get; set; }
    }
}
